### ISSUE TITLE
Initial load re-rendering issue(?) in a universal found-relay-based app

### ISSUE THREAD

**Issue by peet86** [relay-tools/found-relay#135]
Hey,

I have a (probably lame) question concerning how async rendering works with found-relay and why I have some kind of double rendering during the initial load of my universal app. (My app's core is really similar to the found-modern-universal example).

When I first load the app it has SSR + on client-side React hydrate: SSR renders /pageA, the client js kicks in, hydrates the app, render method runs in PageA. Everything looks fine already.. but then a second render occurs in PageA with exactly the same props. O.o 

This second render never happens when I navigate from /pageA to /pageB or back (on client-side)..  In that case everything works "normal".

I'm confused.. first I thought re-rendering happens only in case relay data is not present for the route and the router has to wait for the async response and re-render the component.

But in a universal app at the initial page load all the necessary data is present in the relay payload (from SSR) and the route shouldn't load anything async..  so I don't get it why the extra rendering happens..

Is this a normal behaviour? If not, how can I avoid it? 

found-relay: 0.3.0-alpha.12
relay: modern 1.4.1
react: 16.1.1

**Comment by taion** [comment]
That doesn't sound normal to me. Are you sure you're doing the `await createInitialFarceRouter` thing?

**Comment by peet86** [comment]
Yes, I'm doing it. My init function is async and the createInitialFarceRouter is with await.

**Comment by taion** [comment]
If you set breakpoints in the universal example, do you observe the same behavior? Is it possible you're dispatching some actions or otherwise re-mounting the router?

**Comment by taion** [comment]
Any update?

**Comment by taion** [comment]
Closing for staleness.
