### ISSUE TITLE
Can not pass props to down

### ISSUE THREAD

**Issue by Khangeldy** [relay-tools/found-relay#141]
Hello . I have this  root query
 ```javascript
const rootQuery = `query routesOrdersQuery{ ....Orders_query}`
```
then render it 
```javascript
<Route component={Orders} query={rootQuery} />
```
Orders.js
```javascript
export default  createRefetchContainer(Orders,
 graphql`orders(first: 10) @connection(key: "Orders_orders") {
  edges {
     node {
        id
        text
        from
    }
  }
 }`
)
```
But in Orders component i get nothing. It seems found-relay not support fragment spreading on root query, or i need someway pass props to like 
```javascript
<QueryRenderer
render={({error, props}) => {
          if (error) {
            return <div>{error.message}</div>;
          } else if (props) {
            return <Orders query={props.query} />;
          }
          return <div>Loading</div>;
        }}
...
```

**Comment by Khangeldy** [comment]
Last assumtion was right.

**Comment by taion** [comment]
the renderers here do automatically spread through props, so i don't think it's that render method. you may just need to make sure all the names line up, though. but see https://github.com/relay-tools/found-relay/blob/8d6a85616c00cc01f35b33928ced6c51649236ad/src/modern/renderElement.js#L34 for the default render logic

**Comment by Khangeldy** [comment]
I comprehend it. I should go through all Orders and map them to `<Order order={order.node} />`. And in the `Order.js` create fragmentContainer. In this case everything works perfect. I assumed that relay automaticly did for me. Thanks to all.
