### ISSUE TITLE
Relay 1.6 Compatibility and alpha.13

### ISSUE THREAD

**Issue by adeperio** [relay-tools/found-relay#146]
Hi @taion 

I just tried upgrading to Relay 1.6 and hence went to found-relay alpha.13. But I ended up running against the following error. Wondering if you had any idea what this might be, or if you had seen it at all?

![image](https://user-images.githubusercontent.com/1326430/42695926-18137058-86fa-11e8-9b85-97ac8596ff15.png)

**Comment by taion** [comment]
That's odd. Can you check that you have `found` installed correctly?

**Comment by adeperio** [comment]
That was it. Sorry should have picked that up. Thanks!
