### ISSUE TITLE
Handling nested queries.

### ISSUE THREAD

**Issue by MartinDawson** [relay-tools/found-relay#148]
Routing:
```js
    <Route path="/" {...prepareRouteConfig(AppConfig)} >
      <Route path={paths.unit} {...prepareRouteConfig(UnitDetailsConfig)} />
    </Route>,
```

App:
```js
const Component =   withContext({
    currentUser: PropTypes.object,
  }, ({ currentUser }) => ({ currentUser })),
)(App);

const query = graphql`
  query AppRouteConfig_Query {
    currentUser {
      ...ContactFormContainer_currentUser
    }
  }
`;

export default {
  query,
  Component: AppContainer,
};
```

```js
export const query = graphql`
  query UnitDetailsRouteConfig_Query ) {
    // irellevant fragment code here
  }
`;

export default {
  asyncName: 'UnitDetailsContainer',
  query,
};
```

User login mutation:

```js
const mutation = graphql`
  mutation LoginMutation($input: LoginInput!) {
    login(input: $input) {
      currentUser {
        ...ContactFormContainer_currentUser
      }
    }
  }
`;

const updater = (store) => {
  const loginPayload = store.getRootField('login');
  const root = store.getRoot();

  const userPayload = loginPayload.getLinkedRecord('currentUser');
  root.setLinkedRecord(userPayload, 'currentUser');
};

function commit(input) {
  return createMutation(mutation, { input }, null, null, updater);
}
```

ContactFormContainer:

```js
const enhance = compose(
  getContext(
    { currentUser: PropTypes.object },
  ),
  fragment({
    currentUser: graphql`
      fragment ContactFormContainer_currentUser on User {
        id
        name
        salutation
        firstName
        lastName
        email
        telephone
        company
      }
    `,
  }),
);
```

The user can login and logout. We handle the query for the user on the top level (AppRoute query) and pass the fragment down through React's context API. The problem is we also nest other queries beneath this for each route (I think this may be bad?) and subsequently the nested routes are not re-rendering once the user has updated and we need to them re-render because we use the user in the nested routes.

How do we handle this?

**Comment by taion** [comment]
The nested queries are fine – the ability to do nested queries and have them resolve in parallel is the point of this library.

For refetching, see https://github.com/relay-tools/found-relay/issues/101#issuecomment-347306457.

I'd like to have a better API here than "set a dummy variable", but I can't really think of anything. I think we usually do not want to refetch when avoidable.

**Comment by MartinDawson** [comment]
That's not the issue i don't think.

The issue is when I log in the user gets updated in the context but the child routes withContext never get called. I don't want to refetch anything in the child routes I just want them to get my user from the context.

**Comment by taion** [comment]
Ah, in that case it's the typical problem with the implicit pure Redux containers.

Have you tried using the new context API, or some sort of publish/subscribe pattern? I'm assuming you're using the old context API right now?

**Comment by MartinDawson** [comment]
@taion Good point. I'm using recompose withContext which is 10 months old so I imagine it's the old one.

I'll try the new one. Thanks.

**Comment by taion** [comment]
You could also just use Redux for this sort of data. See https://github.com/4Catalyzer/found#redux-integration.
