### ISSUE TITLE
Prop Types for Component prop on Route

### ISSUE THREAD

**Issue by viktorivarsson** [relay-tools/found-relay#153]
Hi, I'm getting warnings on Routes when I'm setting things up with Relay Modern.

It is working, but the Prop Types for Component is failing with message
```
Warning: Failed prop type: Invalid prop `Component` of value `[object Object]` supplied to `ReadyStateRenderer`, expected an element type (a string or a ReactClass).
    in ReadyStateRenderer
```

When I console.log the component I want to use, I get `$$typeof: Symbol(react.forward_ref)`.

```javascript
const DumbComponent = () => <div>Hello</div>;

const FragmentComponent = createFragmentContainer(DumbComponent, {
  viewer: graphql`
    fragment router_viewer on Viewer {
      id
    }
  `
});

console.log(DumbComponent); // [Function: DumbComponent]
console.log(FragmentComponent); // { '$$typeof': Symbol(react.forward_ref), ...}

export const routeConfig = makeRouteConfig(
  <Route path="/" Component={App}>
    <Route
      path="*"
      Component={FragmentComponent}
      query={graphql`
        query router_TestQuery {
          viewer {
            ...router_viewer
          }
        }
      `}
    />
  </Route>
);
```

Am I doing something wrong, or should the Prop Types be updated to support forward_ref or something?

I'm using
- React 16.4.2
- React DOM 16.4.2
- Found 0.3.14
- Found Relay 0.3.0

**Comment by taion** [comment]
This was fixed through updating prop-types-extra. I bumped the minimum dependency version in [v0.3.1](https://github.com/relay-tools/found-relay/releases/tag/v0.3.1).

**Comment by viktorivarsson** [comment]
Works great now, thank you for the help! 👍
