### ISSUE TITLE
Progress bar from link click to render with props performed

### ISSUE THREAD

**Issue by patrick-samy** [relay-tools/found-relay#156]
What would be a reliable way to trigger a progress bar after clicking a `found` link, and getting a callback when Relay requests are satisfied and/or the component has been rendered.

**Comment by taion** [comment]
See https://github.com/4Catalyzer/found/tree/master/examples/global-pending

this doesn't render a progress bar (instead it greys out the page), but you can use the same logic

**Comment by GrigoryPtashko** [comment]
@taion but in that example the `createBrowserRouter` is used. I use (as also written in the Found Relay doc) the `createFarceRouter` function. But the doc for the `createFarceRouter` says that "It ignores the `renderPending` ...". So how to this global pending pattern with Found Relay and the `createFarceRouter` function?

**Comment by taion** [comment]
Currently, you'll want to pass in a `render` function created by `createRender`, which takes `renderPending` as an option. See https://github.com/4Catalyzer/found#createfarcerouter. We'll change `createFarceRouter` to take `renderPending` directly soon, though, but you can already get the functionality right now with the above.
