### ISSUE TITLE
RedirectException doesn't not work

### ISSUE THREAD

**Issue by rklhui** [relay-tools/found-relay#158]
I am trying to redirect by throwing RedirectException in render when encounter Relay error, but somehow only the root route ("/") works, and any route within doesn't work.

I am also seeing the uncaught (in promise) error from asyncToGenerator, is this the intended behaviour?

Here is my Route:

```
  <Route
    path="/"
    Component={Layout}
    query={LayoutQuery}
    render={({ props, Component, error }) => {
      if (error) {
        throw new RedirectException("/login")
      }
      if (props) {
        return <Component {...props} />
      }
    }}
  >
    <Route
      path="push"
      Component={Push}
      query={PushQuery}
      prepareVariables={(params, { location }) => {
        return {
          ...params,
        }
      }}
      render={({ props, Component, error }) => {
        if (error) {
          console.log("error", error)
          throw new RedirectException("/login")
        }
        if (props) {
          return <Component {...props} />
        }
      }}
    />
  </Route>
```
And seems like when the `Layout` root route encounter the error, the `Push` route error would not be triggered (and logged). I tried removing the query and render part of the `Layout` root route, the error is logged from the `Push` route now, but still no redirect.

Any help would be much appreciated. Thanks so much.

**Comment by taion** [comment]
The `render` calls do get run in order, so if the parent throws an exception, as you'd expect normally, the child `render` methods won't get called.

Otherwise check the `resolving` property on the render args – throwing Found exceptions doesn't currently work when this property is not set.

**Comment by rklhui** [comment]
I see, then how do I do a redirect (to `/login`) if I enter `/push` route with error triggered in the `Layout` route?

**Comment by taion** [comment]
You could lay out your routes like:

```js
<>
  <Route path="/" {...layoutRouteProps} render={renderWithThrow} />
  <Route path="/" {...layoutRouteProps} render={renderWithoutThrow}>
    <Route path="push" {...pushRouteProps} />
  </Route>
</>
```

In this case, the waterfall will skip `renderWithThrow` when matching the push route. Otherwise, as with any imperative JS code, the first exception thrown "wins".
