### ISSUE TITLE
Support Relay v2.0.0

### ISSUE THREAD

**Issue by johntran** [relay-tools/found-relay#159]
Hi there,

At the time of writing this issue, Relay is on 1.7.0-rc.1, so it is a little early to fix.

I attempted to load up Relay 1.7.0-rc.1 with found-relay, and it is erroring here:

https://github.com/facebook/relay/blob/98e866f5e0fc3548f0577bf081df0507832b15f9/packages/react-relay/modern/buildReactRelayContainer.js#L80

with an error of `.unstable_read` is not a function

I think its because found-relay expects the legacy Context API, while Relay is using the new Context in React 16.

Reference to `Context.unstable_read`: https://github.com/facebook/react/pull/13139

Any thoughts?

Though it is possible that its not a problem of found-relay, but its just that the Relay master branch is unstable. I thought it would be related to found-relay because its erroring on components that are used as routes.

**Comment by taion** [comment]
Yeah, I think we'll need to release a breaking change here to move to the new context API, if Relay 1.7.0 does.

**Comment by GrigoryPtashko** [comment]
Are there any plans on Relay 2.0.0 support? I want to upgrade my app to the newest version of Relay (I'm using Found Relay).

**Comment by GrigoryPtashko** [comment]
Yeah, I'm on 2.0.0-RC1 in my mobile app. But in the webapp I'm on 1.4. I want to upgrade 1.4 to 2.0.

**Comment by wkerswell-gresham** [comment]
V2 was released 2 days ago so probably safe to upgrade now. Is there plans to update this soon?

**Comment by taion** [comment]
nice, i'll work on upgrading

**Comment by taion** [comment]
oh, that would be great – please do!

**Comment by taion** [comment]
resolved in #167
