### ISSUE TITLE
TypeError: [object Object] is not iterable! 

### ISSUE THREAD

**Issue by GrigoryPtashko** [relay-tools/found-relay#160]
Hello.

I've upgraded my app to:

1. relay 1.7.0
2. found 0.3.14
3. found-relay 0.3.1

To make things simple here's the shortened version of my router (which worked prior to upgrade):

```
        this.AppRouter = createFarceRouter({
          historyProtocol: new BrowserProtocol(),
          historyMiddlewares: [queryMiddleware],
          routeConfig: makeRouteConfig(
            <Route
              path="/"
              Component={appHoc(vReconnectingCbo, hideNavCbo)}
              query={graphql`
                query main_App_Query {
                  root {
                    ...App_root
                  }
                }
              `}
            >
              <Route path="welcome" Component={Welcome} />
              <Route path="myaccount" Component={MyAccount} />
            </Route>
          ),

          render: createRender({})
        });
```

But I get the exception:

```
[Error] Unhandled Promise Rejection: TypeError: [object Object] is not iterable!
	dispatchException (app.js:71859)
	invoke (app.js:71590)
	step (app.js:1847)
	initializePromise
	Promise
	F (app.js:2569)
	(anonymous function) (app.js:1844)
	componentDidMount (app.js:14906)
	commitLifeCycles (app.js:57718)
	commitAllLifeCycles (app.js:59018)
	callCallback (app.js:41921)
	dispatchEvent
	invokeGuardedCallbackDev (app.js:41971)
	invokeGuardedCallback (app.js:42028)
	commitRoot (app.js:59214)
	completeRoot (app.js:60670)
	performWorkOnRoot (app.js:60599)
	performWork (app.js:60507)
	performSyncWork (app.js:60481)
	requestWork (app.js:60350)
	scheduleWork (app.js:60159)
	enqueueSetState (app.js:54085)
	setState (app.js:69115)
	resetRelayEnvironmentCb (app.js:104177)
	_callee$ (app.js:103991)
	tryCatch (app.js:71363)
	invoke (app.js:71598)
	asyncGeneratorStep (app.js:103899:104)
	_next (app.js:103901:213)
	promiseReactionJob
```

Here's the screenshot from the console:

![screen shot 2018-12-08 at 10 22 05](https://user-images.githubusercontent.com/2768788/49683308-7ef79b80-fad3-11e8-9aed-b8b9b42b40ce.png)

While debugging I noticed that if falls somewhere here:

https://github.com/4Catalyzer/found/blob/master/src/utils/resolveRenderArgs.js#L52

But I don't understand why.

Any ideas?

Thanks!

**Comment by GrigoryPtashko** [comment]
Guys, anyone? Found Relay is really great but this one is really a stopper for me 😕

**Comment by hisapy** [comment]
No idea ...  If possible, I'd downgrade to the prior working version to avoid _the stopper_ until someone finds the cure or I have time to debug deeply.

**Comment by hisapy** [comment]
I noticed the error is in the runtime.js. I think this is webpack's runtime. Perhaps, it could be something related to babel or a webpack config ... just thinking

**Comment by GrigoryPtashko** [comment]
I've got babel 7 and webpack 4 installed.

```
    "@babel/core": "^7.2.0",
    "@babel/plugin-proposal-class-properties": "^7.2.0",
    "@babel/plugin-transform-flow-strip-types": "^7.2.0",
    "@babel/preset-env": "^7.2.0",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.4",
...
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.9"
```

It's in the __DEV__ mode. Previously, I used babel 6 and webpack 4 with an older version of Found Relay and it worked.

**Comment by taion** [comment]
It's likely the Babel upgrade. Can you check that the ES7 symbol polyfill is getting correctly applied?

Also, you're importing from `lib/` here, not `src/`?

**Comment by GrigoryPtashko** [comment]
@taion can you, please, tell me how to check the ES7 symbol polyfill?
I'm using `@babel/preset-react`, `@babel/preset-env`. And two plugins `babel/plugin-transform-flow-strip-types`, `@babel/plugin-proposal-class-properties`.


And yes, `lib/`:

```
import makeRouteConfig from "found/lib/makeRouteConfig";
import Route from "found/lib/Route";
import BrowserProtocol from "farce/lib/BrowserProtocol";
import queryMiddleware from "farce/lib/queryMiddleware";
import createFarceRouter from "found/lib/createFarceRouter";
import createRender from "found/lib/createRender";
import withRouter from "found/lib/withRouter";
import { Resolver } from "found-relay";

```

**Comment by GrigoryPtashko** [comment]
I'm using the `"babel-polyfill": "^6.26.0",`

and in the webpack config I've got this:  `entry: ["babel-polyfill", "./src/main.js", "./style/style.scss"],`

**Comment by taion** [comment]
That's likely to do quite odd things if you're using preset-env with Babel 7. Try explicitly pulling in `core-js/es7/symbol` in your entry point.

**Comment by GrigoryPtashko** [comment]
@taion that did the trick! Thank you very much! I've installed `"core-js": "^2.6.0",` and added to webpack config `entry: ["core-js/es7/symbol", ...`.
