### ISSUE TITLE
How to access route variables in Component

### ISSUE THREAD

**Issue by leoschweizer** [relay-tools/found-relay#161]
I'm rendering a Relay refetch container which takes fragment variables to specify a date range for which data shall be displayed. On the initial render, I want this date range to be now + some time interval, and I'm successfully using prepareVariables to inject these dynamic values. After the initial render, the user can select a date range through the UI, and a refetch can be triggered.

The problem is: I need to know the output of prepareVariables inside the rendered component. Imagine I wanted to pre-fill the date selection controls with the beginning and end dates which have dynamically been determined in prepareVariables.

How can I access those variables? It looks like they aren't exposed anywhere in match / location / etc.

Notice that those variables aren't actually route parameters - but I'm not aware of another place where I could inject the initial Relay query variables.

**Comment by taion** [comment]
Yeah, these aren't really exposed in a great way right now. You could in principle read them off the Relay environment, I guess.

The correct approach would probably be to pass in `querySubscription.relayContext.variables` at https://github.com/relay-tools/found-relay/blob/v0.3.1/src/modern/Resolver.js#L187-L194

Then thread that through to the `route.render` call in https://github.com/relay-tools/found-relay/blob/v0.3.1/src/modern/renderElement.js#L37-L43

Care to take a stab at PRing this?

**Comment by leoschweizer** [comment]
I can give it a try - but probably not until next year :wink:

**Comment by taion** [comment]
resolved in #166
