### ISSUE TITLE
Root level queries?

### ISSUE THREAD

**Issue by HorizonShadow** [relay-tools/found-relay#173]
If you have a route query like 

```
        <Route path={'replays'}
               Component={ReplaysPage}
               query={graphql`
                   query RoutesQuery {
                      ...ReplaysPage_query
                   }
               `}
        />
```

The query prop in this case is `nil` in the fragment container.

In a query renderer, you would return something like 

```
render={({error, props}) => {
            if(error) {
                return "error";
            }
            if(!props) {
                return "loading";
            }
            console.log(props);
            return <ReplaysPage query={props} />
        }}
```

Not really sure why the query would be nil when using found-relay. Can you point me in the right direction?

**Comment by taion** [comment]
This is the code that handles getting props off query data: https://github.com/relay-tools/found-relay/blob/63d7cf3d14a2a7f3b106d060bbd13d7a11af95e3/src/QuerySubscription.js#L129-L135

This should match the logic in `<QueryRenderer>` upstream though! https://github.com/facebook/relay/blob/27b3433934dcec084e0b8ec77ede89e86d009031/packages/react-relay/ReactRelayQueryRenderer.js

**Comment by HorizonShadow** [comment]
It looks like with that code, the data key would be null, since `snapshot.data` would be the response you actually want to pass?

**Comment by taion** [comment]
What do you mean the "data key"? `snapshot.data` will be the actual query payload, no?

**Comment by HorizonShadow** [comment]
Right, but it will contain the fragment, without a top level accessor.

For example,

```
{
  viewer {
    ...SomeFragment_viewer
  }
}
```

"SomeFragment" would be exposed on `viewer`. So the response would be something like `data.viewer = { /* the fragment stuff */ }`

In this case,

```
{
  ...SomeFragment_query
}
```

You would end up with `data = /* the fragment stuff */. So the props *are* the response, rather than `props.query` being the response, I think.

**Comment by taion** [comment]
Wait, so why not just do the same thing as the `<QueryRenderer>` case and pass through `query={props}`?

**Comment by HorizonShadow** [comment]
Ah. Somehow I managed to miss the render prop every time I went over the readme. 

Sorry for that. Thanks for your help!
