### ISSUE TITLE
Uncaught Invariant Violation: commitRelayModernMutation: expected `environment` to be an instance of `RelayModernEnvironment` 

### ISSUE THREAD

**Issue by arjun-kava** [relay-tools/found-relay#179]
I am using `found-relay` as router such as below:

```javascript
import makeRouteConfig from 'found/lib/makeRouteConfig';
import Route from 'found/lib/Route';
import React from 'react';
import { graphql } from 'react-relay';

import TodoApp from '../components/todo/TodoApp.Component'
import TodoList from '../components/todo/TodoList.Component'


const TodoListQuery = graphql`
  query routes_TodoList_Query($status: String!) {
    viewer {
      ...TodoList_viewer
    }
  }
`;

export default makeRouteConfig(
<Route
    path="/"
    Component={TodoApp}
    query={graphql`
      query routes_TodoApp_Query {
        viewer {
          ...TodoApp_viewer
        }
      }
    `}
  >
    <Route
      Component={TodoList}
      query={TodoListQuery}
      prepareVariables={params => ({ ...params, status: 'any' })}
    />
    <Route path=":status" Component={TodoList} query={TodoListQuery} />
    <Route path="home" Component={TodoList} query={TodoListQuery} ></Route>
  </Route>,
);
```

Then I am accesing `relay.enviroment` from `props` such as below:
```javascript
 const { relay, viewer } = this.props;
```
 It's throwing error: Uncaught Invariant Violation: commitRelayModernMutation: expected `environment` to be an instance of `RelayModernEnvironment` 

while, working If I directly import it rather than acessing from `props`.

I am new to Relay, any suggestions will be appreciated. You can also put reference link on comment. Thank You.

**Comment by taion** [comment]
What do you mean by importing it directly?

How are you setting up the environment, and are you using the correct version of Relay matching the version of this library?

**Comment by arjun-kava** [comment]
Hello, @taion 
I have used the latest alpha, due to the support of relay modern:
"found-relay": "^0.4.0-alpha.4" 
"found": "^0.3.21"
"farce": "^0.2.7"
"relay-runtime": "^3.0.0"
"react-relay": "^2.0.0"

Thank you for the response.

**Comment by taion** [comment]
Your versions of react-relay and relay-runtime are incompatible. Use the same version for both.

**Comment by arjun-kava** [comment]
I had updated versions as below:
```
"react-relay": "^3.0.0",
"relay-runtime": "^3.0.0",
"babel-plugin-relay": "^3.0.0",
"relay-compiler": "^3.0.0",
```
Still throws same error. Do I have to update any other version? Thank you for the help.
