### ISSUE TITLE
Support Relay v3.0

### ISSUE THREAD

**Issue by adin-ttc** [relay-tools/found-relay#180]
Any idea if this is being worked on already?

**Comment by taion** [comment]
It already works. I just need to update the peer dep.

**Comment by taion** [comment]
With the alpha, I mean

**Comment by adin-ttc** [comment]
any idea on when alpha will be beta/rc?

**Comment by taion** [comment]
i want to make a few more API changes... the alpha is largely ready to use and it's what we're using, though.

this is resolved in https://github.com/relay-tools/found-relay/pull/181 at any rate

**Comment by adin-ttc** [comment]
Thanks for the info, I just tested with the alpha and 3.0 seems to be working
