### ISSUE TITLE
Pass environment to render

### ISSUE THREAD

**Issue by hisapy** [relay-tools/found-relay#195]
This is a feature request.

Pass environment to render either in props or explicitly. 

This would be useful when the rendered component isn't any Relay container, but internally it needs the environment to commitMutation or similar operations.

**Comment by taion** [comment]
This sounds reasonable, but I don't quite understand your use case. Why not just render a Relay component in the route?

**Comment by hisapy** [comment]
Well, in my case, I've a `Form` wrapping a `Card` ... the query is something like

```
query routeQueries_Form($id: ID!, $newRecord: Boolean!) {
    data: node(id: $id) @skip(if: $newRecord) {
      ...Card_data @relay(mask: false)
    }
  }
```

Of course I could just wrap the form inside a Fragment container but I was thinking I could keep it simple by just getting the `environment` from `render` in my `Route`. 

And thinking it better, if this feature is to be implemented it should actually be separated from the `props` and given explicitly. 

I'll let you think about it. In the meantime I'm deciding to pass the environment via a fragment container or a React context I'm already using for auth.

**Comment by hisapy** [comment]
Actually, it's very annoying having to render a Relay fragment container without data. Since no data is fetched I get the typical warning like

```
warning.js:30 Warning: createFragmentSpecResolver: Expected prop `data` to be supplied to `Relay(Form)`, but got `undefined`. Pass an explicit `null` if this is intentional.
```

and what's worst is that the `data` is set to null by Relay and thus, the component's `defaultProps.data` is not used. 

So please, can we get the `environment` in `render`?

**Comment by taion** [comment]
if you're rendering a component anyway, though, you can just get the env off the context – use `ReactRelayContext` from `react-relay`; any route with a query gets one set up

the only case where you'd need `environment` in `render` is if you were trying to directly do something with the environment _in_ `render`; any other component can just read it from context

**Comment by hisapy** [comment]
Thx @taion 

In case someone else needs it, here is how I've got it

```javascript
import React, { useContext } from "react";
import { ReactRelayContext } from "react-relay";
// other imports here

const Form = props => {
  const { environment } = useContext(ReactRelayContext);

  // do stuff with context 

  return (
    <form>
      <Card ... />
    </form>
  )
}
```

I'm closing this issue, though, just for the record, I think I'd prefer to get the environment explicitly in `render` in `Route`. Using the context this way seems a little bit _magical_ because the context is provided internally by `found-relay` and not by the developer using the lib. If I were using `QueryRenderer` directly, I would've to get/set the `environment` and normally, it would've been available in the render prop as well.

**Comment by taion** [comment]
`<QueryRenderer>` doesn't include `environment` in the props it passes down, though, as far as I know?

This context is actually provided by all Relay containers, though – so this would work the same if using `<QueryRenderer>`.

**Comment by hisapy** [comment]
I mean

```javascript

const environment = getYourEnvironment();

return (
    <QueryRenderer
      environment={environment}
      variables={variables}
      query={query}
      render={({props, error}) => {
        // you can also use environment here and pass it to the component to render no matter wether is a Relay container or not
      }}
    />
  );

```

**Comment by taion** [comment]
okay, that's a good idea
