### ISSUE TITLE
Queries without specifying nested queries 

### ISSUE THREAD

**Issue by fameoflight** [relay-tools/found-relay#216]
In react-router-relay I never needed to define the children component queries in the main route 

`
ViewerQuery = {
  viewer: () =>
    Relay.QL`
      query ViewerQuery{
        viewer
      }
    `
}
`

And react-router-relay will collect all the children viewer queries any way to replicate this magic here?

**Comment by taion** [comment]
When using Relay Modern, no. The automatic composition was a Relay Classic behavior that react-router-relay was simply exposing. In Relay Modern, you must specify composed fragments explicitly.
