### ISSUE TITLE
Can't resolve 'react-relay/lib/RelayPropTypes'

### ISSUE THREAD

**Issue by Khangeldy** [relay-tools/found-relay#217]
I created project with create-react-app. And then configured babel relay. Installed found, `found-relay`. And after starting project in console i get this error `Can't resolve 'react-relay/lib/RelayPropTypes'` . Then I upgraded package with `yarn upgrade found-relay@next` hoping that resolve this problem. But i get another runtime error `Cannot read property 'operationKind' of undefined`. Can you help me? What i am doing wrong?

**Comment by taion** [comment]
This library doesn't explicitly reference `operationKind`. Most likely what's happening here is that there's some sort of mistake in your transpilation setup, in that you're not correctly compiling GraphQL tags. Check your transpiled code and see what's happening to your `graphql` tag calls.
