### ISSUE TITLE
How to support a dynamic menu with page content

### ISSUE THREAD

**Issue by wkerswell-gresham** [relay-tools/found-relay#226]
Hi, I am trying to workout how to structure my routing so that I can have a sidebar with menu items that are populated from a GQL query and have content area populated with another query.  If I have them both in the same query on one route whenever I select a menu item I will get the content needed but will get all the data back for the menu too which seems like a lot of overhead. 
 
![Screenshot 2019-04-23 at 11 33 28](https://user-images.githubusercontent.com/20516520/56575095-cda65d80-65bc-11e9-8b1f-fa7c19fdcfc2.png)

What I am aiming for is to be able to update the productID in the URL have the content change but not the sidebar.

**Comment by taion** [comment]
Take a look at https://github.com/4Catalyzer/found#named-child-routes.

In this context, you'd set up a named child group where the "menu" named route matches everything (and which drops the unnecessary params from variables – I think that might be required), while a different "product" named route handles each product.

**Comment by wkerswell-gresham** [comment]
Thanks! Will look into that.

**Comment by wkerswell-gresham** [comment]
Named children was what I was after. Thanks for your help

**Comment by wkerswell-gresham** [comment]
Hey, With the update to `found: 0.4.0` my named child route has stopped working. Has there been any changes in that area? 

if I go to `/products` I get an empty page if I got to `/products/someID` it works as expected. 

```
        <Route
            path="products"
            query={ProductsQry}
            prepareVariables={() => ({
                filter: {},
            })}
            Component={Products}
            render={renderArgs => (
                renderedComponent(
                    renderArgs,
                    null,
                    ProductsLoader,
                )
            )}>
            {{
                productView: <Route
                    path=":productId"
                    query={ProductQry}
                    prepareVariables={params => ({
                        productId: params.productId,
                    })}
                    Component={Product}
                    render={renderArgs => (
                        renderedComponent(
                            renderArgs,
                            null,
                            ProductLoader,
                        )
                    )} />,
            }}
        </Route>
```

`renderedComponent()` Is a helper to show a loader 
```
const renderedComponent = (
    { Component, props },
    messageProps,
    Loader,
) => {
    if (!Component || !props) {
        return (
            <Fragment>
                {
                    messageProps
                        ? (
                            <TitleLoader>
                                <FormattedMessage {...messageProps} />
                            </TitleLoader>
                        )
                        : null
                }
                <Loader />
            </Fragment>
        );
    }
    return <Component {...props} />;
};
```

**Comment by taion** [comment]
Note the breaking changes in the release log: https://github.com/4Catalyzer/found/releases/tag/v0.4.0

Found v0.4.0 no longer matches "stem" routes, as this could lead to more routes matching than desired. Instead, add a `<Route />` as the first child of your parent route above. Then that will match.

**Comment by wkerswell-gresham** [comment]
Thanks for the quick response. That makes sense. 

Does this look how you would expect? 

```
        <Route
            path="products"
            query={ProductsQry}
            prepareVariables={() => ({
                filter: {},
            })}
            Component={Products}
            render={renderArgs => (
                renderedComponent(
                    renderArgs,
                    null,
                    ProductsLoader,
                )
            )}>
            <Route />
            <Route>
                {{
                    productView: <Route
                        path=":productId"
                        query={ProductQry}
                        prepareVariables={params => ({
                            productId: params.productId,
                        })}
                        Component={Product}
                        render={renderArgs => (
                            renderedComponent(
                                renderArgs,
                                null,
                                ProductLoader,
                            )
                        )} />,
                }}
            </Route>
        </Route>
```

**Comment by taion** [comment]
Yup.
