### ISSUE TITLE
Months and still no beta or RC?

### ISSUE THREAD

**Issue by adin-ttc** [relay-tools/found-relay#276]
It's been months since alpha 1 (Jan 11) and we're still on Alpha (June 14). Is there a plan to go to Beta or RC? 

I have Alpha 8 and things seem to work great! I do not have any issues and the code seems stable. Some organizations don't like releasing Alpha code though! Is there anything that is holding up development RC and can the broader community work on these issues? Why is it still regarded as Alpha? 

I appreciate all the effort that goes into this, however, if it looks like this project is not going to be moving forward, the broader dev community will be looking at other options.

With great respect I ask if you could please provide and update or a timeline on release?

**Comment by taion** [comment]
Cutting a proper release now.

**Comment by taion** [comment]
https://github.com/4Catalyzer/found/releases/tag/v0.4.0
https://github.com/relay-tools/found-relay/releases/tag/v0.4.0

**Comment by adin-ttc** [comment]
Thanks for the quick turn-around on this!

**Comment by taion** [comment]
It was just fear of commitment on my part. I'll try harder on not leaving stuff in alpha forever. We've been on the alphas from the start.
