### ISSUE TITLE
Code splitting: "Invariant Violation: RelayModernGraphQLTag: Expected a request, , got `{}`" when using async getQuery

### ISSUE THREAD

**Issue by dminkovsky** [relay-tools/found-relay#294]
In `Thread.js`

```
export const threadQuery = graphql`
    # some query
`;
```

**Fails:**
```
{
        path: '/message',
        getComponent: async () => {
                const module = await import('./Thread');
                return module.default;
        },
        getQuery: async () => {
                const module = await import('./Thread');
                return module.threadQuery;
        },
},
```

<img width="796" alt="Screen Shot 2019-06-30 at 7 34 11 AM" src="https://user-images.githubusercontent.com/218725/60395984-7b784000-9b09-11e9-84af-ec2076ec432e.png">

Does `getQuery()` have to be sync? 

<img width="866" alt="Screen Shot 2019-06-30 at 7 39 47 AM" src="https://user-images.githubusercontent.com/218725/60396075-ce062c00-9b0a-11e9-9c64-a4341215cd43.png">

Thank you

PS. Obviously not a blocking issue.

**Comment by taion** [comment]
We don't currently support async `getQuery` calls. In general this is not necessarily what you'd want anyway. It seems that in most code splitting use cases, it makes more sense to have the query in the main bundle, and fetch both the data and the new code in parallel, as opposed to waiting for the code fetching to complete before requesting the data.

**Comment by dminkovsky** [comment]
Ah makes a lot of sense. Thank you.

**Comment by taion** [comment]
Tracking this as a feature request in https://github.com/relay-tools/found-relay/issues/297
