### ISSUE TITLE
Feature request: support defer

### ISSUE THREAD

**Issue by dminkovsky** [relay-tools/found-relay#301]
I've moved all my queries into my route config, except one. My "bootstrap" query. It must run first, then all other queries can run in parallel.

**Comment by taion** [comment]
We may be able to something like this already. Can you clarify:

- When will this query run? On page load, on user login, on every navigation action, or what?
- What sort of feedback do you want to show to the user while the bootstrap query is running?

**Comment by dminkovsky** [comment]
> When will this query run? On page load, on user login, on every navigation action, or what?
When the page loads
> What sort of feedback do you want to show to the user while the bootstrap query is running?
None/doesn't matter

**Comment by taion** [comment]
Hmm, couldn't you just independently run this query before mounting the router, then? If it's just a generic bootstrap query, it seems like you wouldn't need the router to handle this for you.

**Comment by dminkovsky** [comment]
Yep, that's what I'm doing right now. With a QueryRenderer so it's pretty convenient (this QueryRenderer renders the Router). Don't need to do this at the router level, and I see now what you're saying: this is not route-related, so maybe it doesn't make sense to include it in route config. Just seemed kind of nice for some reason, but maybe not.

**Comment by taion** [comment]
Right... in this case I personally wouldn't put it in the route config at all if it's just app-level bootstrapping required to build the other queries.

Even with the implementation in the default Found resolver, you wouldn't really have a great way of using the data _from_ the bootstrap query for anything. As I'm assuming that's what you'd want to do, I think we'd need more thinking w/r/t how the API here should look to actually enable the specific use case.

**Comment by dminkovsky** [comment]
> Even with the implementation in the default Found resolver, you wouldn't really have a great way of using the data from the bootstrap query for anything.

Just to clarify: The bootstrap query only composes fragments and provides a context for those fragments to be used:

<details>

```js
import React from 'react';
import {QueryRenderer, graphql} from 'react-relay';
import {Resolver} from 'found-relay';
import {hot} from 'react-hot-loader/root';

import BootstrapContext from './BootstrapContext';
import Router from './Router';

class Bootstrap extends React.Component {
    static displayName = 'Bootstrap';

    render() {
        const {environment, environmentReset} = this.props;
        const resolver = new Resolver(environment);
        return (
            <QueryRenderer
                environment={environment}
                query={query}
                variables={{}}
                render={({props}) => {
                    if (!props) {
                        return null;
                    }
                    return (
                        <BootstrapContext.Provider
                            value={{
                                user: props.user,
                                environment,
                                environmentReset,
                            }}
                        >
                            <Router resolver={resolver} />
                        </BootstrapContext.Provider>
                    );
                }}
            />
        );
    }
}

export default hot(Bootstrap);

const query = graphql`
    query BootstrapQuery {
        user {
            id
            ...Bootstrap_user @relay(mask: false)
        }
    }
`;

graphql`
    fragment Bootstrap_user on User {
        ...AuthStateEnforcer_user
        ...Header_user
        ...Private_user
        ...DeliveryPlaceContainer_user
        ...DeliveryTimeContainer_user
        ...Settings_user
        ...MailboxNextDelivery_user
        ...Mailbox_user
        ...Home_user
    }
`;

```

</details>

and then those fragments are used wherever needed, eg. the header:

<details>

```js
import React from 'react';
import {graphql} from 'react-relay';
import styled from 'styled-components';
import {compose} from 'recompose';

import {bootstrapped} from '../bootstrapped';
import Logo from '../Logo';
import {LoggedOutNav, LoggedInNav} from './HeaderNav';

export default compose(
    bootstrapped({
        user: graphql`
            fragment Header_user on User {
                ...HeaderNav_user
            }
        `,
    }),
)(({user, path}) => (
    <Root path={path}>
        <Logo linked={true} withText={true} style={logoStyle} />
        {user ? <LoggedInNav user={user} /> : <LoggedOutNav />}
    </Root>
));

```

</details>

**Comment by dminkovsky** [comment]
Another motivating factor is SSR. I would really like to get to SSR, and I'm not sure how QueryRenderer handles that.

**Comment by taion** [comment]
Looking at your example again, why can't your bootstrap query just be a top-level route that provides context? i.e. why is it that it must run separately, and first?

**Comment by dminkovsky** [comment]
The bootstrap query is a bad query and potentially has a side-effect. I think it makes sense to close this.

**Comment by taion** [comment]
Wait... so this might be an issue with the docs, but even so, as long as the route doesn't change, Found Relay won't re-run the query, so even if it's "bad", it's not going to get re-run. I'm sorry if I'm missing something here.
