### ISSUE TITLE
what is the best practice regarding preventing full queries in the case of a 404?

### ISSUE THREAD

**Issue by jmcneese** [relay-tools/found-relay#338]
previously with the extraQuery and prerender mechanisms it was trivial to run a short query before a full page query to detect if a route should throw a 404 HttpError, such as /things/:thingId where the extraQuery just checked if the specified thingId actually existed before running the presumably much larger (or nested route's) queries for that component.  how does one go about that without extraQuery/prerender?

similarly, since render isn't async, and I have not discovered any other async hook that will fire before a route's queries are executed, I am finding it similarly difficult to create a true protected route configuration that will throw a 401/403 and redirect to a login page (or just replace the Component with some login component/page).  any hints/tips/tricks that would help me out?

**Comment by jmcneese** [comment]
(to make sure I am understood, my scenario is an /admin route that I would like to be able to designate as protected by checking if the user is logged in and in a specific group, which I can do either via client-side Cognito libraries, or else checking against GraphQL viewer, and then I can put child routes underneath this that have queries that will never be attempted to be executed if the /admin route's protection mechanism fails.  similarly, any route that just needs authentication will not attempt to execute a query if the user is not logged in.  the only thing I can see from the docs and digging in the source is to just allow the query to execute and catch 401/403 errors on the client, and then programmatically route to a login... which seems wasteful and icky.  but I figure I am missing something obvious 🤷‍♂

**Comment by taion** [comment]
`extraQuery` and `prerender` didn't actually run that extra query "before" the main query. They were always dispatched at the same time, and would be run in parallel.

Do the client-side Cognito libraries run synchronously or asynchronously?

**Comment by jmcneese** [comment]
asynchronously.  an example to determine someone's session locally via Cognito would be like:
```
async () => {
  const session = await Auth.currentSession();
  const identity = session.getIdToken().getPayload();
  // do something with some claim in token, like check groups, or some permission
}
```

I would also be running these checks on the server, of course, but I am looking for a way to avoid running potentially large or intensive queries when they are totally irrelevant for the current viewer (like trying to execute an admin-centric query with pagination and filtering, etc etc, when the user isn't an authorized admin or even logged in)

**Comment by taion** [comment]
Okay, so... just keep in mind that this wasn't previously possible with `extraQuery`, and that those queries were all fired off in parallel per https://github.com/relay-tools/found-relay/blob/2b40a7e812a50d760c598a854eb63ebc0b7af6c2/src/classic/Resolver.js#L236

If you wanted to do this right now, I would override the `Resolver`, and do something like:

```js
class Resolver extends ResolverBase {
  async *resolveElements(match) {
    if (isAdminRoute) {
      // check access, which caching, and throw a 404 otherwise
    }

    // This should be a super call, but this works around a Babel bug.
    yield* ResolverBase.prototype.resolveElements.call(this, match);
  }
}
```

Does that make sense?

**Comment by jmcneese** [comment]
yes, that does make sense!  ok cool, I'll give that a shot.  thanks, @taion!

**Comment by jmcneese** [comment]
works like a charm, @taion.  thanks again!
