### ISSUE TITLE
Unit testing components with Jest

### ISSUE THREAD

**Issue by sepans** [relay-tools/found-relay#350]
Hi 👋,

I am trying to add jest tests for some Relay components. I managed to make it to work for a [one](https://github.com/sepans/ctzen/blob/af215a9e91ada5bbacb8c1e55993a220783d1656/src/components/CandidateInfo.spec.tsx) that doesn't have a `found` `Link` but the [other one](https://github.com/sepans/ctzen/blob/af215a9e91ada5bbacb8c1e55993a220783d1656/src/pages/CandidateList.spec.tsx) I am getting 
`TypeError: Cannot read property 'createHref' of undefined`
 along with some props type warnings like 
`Failed prop type: The prop 'match' is marked as required in 'BaseLink', but its value is 'undefined'.`

 But when I remove the `<Link>` from [here](https://github.com/sepans/ctzen/blob/988f2a738501511326c3a990e8675a46e4937bef/src/pages/CandidateList.tsx#L20) it works fine.

My first guess was that the failure was because the test component was not enclosed `Router` but wasn't able to get that far. Do you have any suggestions about how to fix that?  Any help is very much appreciated.

**Comment by sepans** [comment]
I was able to mock the `<Link>` component and resolve the problem:
```js
jest.mock('found', () => ({
  Link: component => <a href={`${component.to}`}>{component.children}</a>
}))
```

That is good enough for snapshot testing. 
Leaving this issue open in case you have better suggestions.

Thanks

**Comment by taion** [comment]
Take a look at https://github.com/4Catalyzer/found/issues/136.

If you're just rendering a link on its own, you'll want to follow the instructions in the linked issue for setting up a mock router context for now.
