### ISSUE TITLE
`getCacheConfig` is running for every route but doesn't seem to update return value

### ISSUE THREAD

**Issue by damassi** [relay-tools/found-relay#495]
Noticing that when running `getCacheConfig` on a route config, the return value of the first execution _only_ is passed in and applied. Subsequent executions of `getCacheConfig` do not modify the return value. Thoughts? If the route config is indeed static, why does is this function invoked for each route change? 

Example: 

```js
{
  getCacheConfig: (params) => {
     let force = false 
     if (params.someArtwork === 'foo') {
       force = true
     } 
 
     return { force }
  }
}
```

Wondering if I'm misunderstanding something, or if this might be a bug.

**Comment by taion** [comment]
Is it possible that the calculated cache config is the only thing that's changing?

To match the behavior on `<QueryRenderer>`, we don't do _any_ refetching if the only thing that's changed is the cache config: https://github.com/facebook/relay/blob/v9.0.0/packages/react-relay/ReactRelayQueryRenderer.js#L141.

**Comment by damassi** [comment]
In this case it turned out the issue is that `getCacheConfig` doesn't support `async`, in which case the correct value is never resolved.
