### ISSUE TITLE
Requery the data

### ISSUE THREAD

**Issue by cutamar** [relay-tools/found-relay#521]
Is there any way to requery the data from my graphql endpoint. My found location query variables are bound to the graphql query variables, and I usually I manage my paginating by `router.push` with the new query variables. The problem is now I need to refresh/refetch the data, similar to a pull-to-refresh function, but using `router.push(match.location)` doesn't work. Are there any easy ways to accomplish this?

**Comment by taion** [comment]
`render` passes down a `retry` callback that you can use to re-fetch the data. You can also do `router.replace`.

**Comment by cutamar** [comment]
@taion worked like a charm using render, thanks
