### ISSUE TITLE
Component query encapsulation

### ISSUE THREAD

**Issue by hexwit** [relay-tools/found-relay#544]
Relay offers to keep query renderer and query inside root component. And that is convenient, and you have encapsulated that in one place. 
Found-relay offers move query to router configuration. That means I have to manage query and root components separately.

What would be the best way to keep query within the component, and provide function for `getQuery` param if my application based on functional components? 

Thanks in advance.

**Comment by taion** [comment]
You can do something like:

```js
MyComponent.query = graphql`...`
```

in the module where you export your component, then just use that in `query`.

This is a bit less friendly for code-splitting, though, as it means you can't e.g. start loading the query data while pulling down the split-out code bundle for the component.
