### ISSUE TITLE
Things to mention in the docs

### ISSUE THREAD

**Issue by taion** [relay-tools/found-relay#56]
- [x] Use `createFarceRouter`/&c. instead of `createBrowserRouter`

**Comment by jpbarela** [comment]
Mention that each route should be thought of as an individual QueryRender and should have it's own render property.

**Comment by taion** [comment]
Mention error handling, because it's confusing.

**Comment by wkerswell-gresham** [comment]
This is going to sound silly but I spent a while looking at the wrong URL before I noticed the example was using `historyProtocol: new HashProtocol()` 
going to `/foo` not `/#/foo` 
Might be worth a mention or updating the example to use `BrowserProtocol`

**Comment by taion** [comment]
@wkerswell-gresham Can you elaborate? I actually added HashProtocol explicitly for the TodoMVC example, because that's what TodoMVC called for.

**Comment by wkerswell-gresham** [comment]
Iy was that I just came from the found example using the `BrowserProtocol` so spent more time than I would like to admit wondering why my URL's were not working after copying the example. Took me a while before I ran up the example rather than looking at the repo and noticed.

**Comment by taion** [comment]
@emwalker You can get by without specifying `render`, BTW – it'll just give you the old Relay Classic behavior of keeping around whatever was previously there until the new page fully loads. Not ideal UX, but it was the best default I could think of. But, yeah, each route is its own `<QueryRenderer>` with its own query.

**Comment by cellis** [comment]
how `prepareVariables` works?
