### ISSUE TITLE
v0.8.3, v0.9.0 and v0.9.1 are deployed to npm but not committed (npm account hacked?)

### ISSUE THREAD

**Issue by Gautierrr** [relay-tools/found-relay#607]
Hi,

Looks like there is a synchronisation problem between npm versions and GitHub versions. Making me thinking that your npm account may have been compromised.

Those versions are published to npm:
- https://www.npmjs.com/package/found-relay/v/0.9.1
- https://www.npmjs.com/package/found-relay/v/0.9.0 (a month ago)
- https://www.npmjs.com/package/found-relay/v/0.8.3 (3 months ago)

However the last git tag is [v0.8.2](https://github.com/relay-tools/found-relay/releases/tag/v0.8.2) released the 24 Jul 2020 (9 months ago)

That's very strange that npm versions keeps popping up but there is no more activity on the repository and @taion (the project owner) stops contributing to GitHub on Aug 25, 2020.

What's going on? Is it safe to install [found-relay](https://www.npmjs.com/package/found-relay) npm packages >0.8.2 ?

Where are the commits?

**Comment by yvele** [comment]
Hum.. yep I'm rolling back to v0.8.2 while waiting for clarification 🤔

**Comment by jquense** [comment]
no hacking, i just forgot to push the commits, should be there now
